# Generated by Django 4.1.2 on 2022-10-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InaraApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commander',
            old_name='member_since',
            new_name='pub_date',
        ),
    ]
