# Generated by Django 4.1.2 on 2022-10-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InaraApp', '0003_alter_station_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ships',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
