# Generated by Django 4.1.2 on 2022-10-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InaraApp', '0004_alter_commander_img_alter_ships_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ships',
            name='img',
        ),
        migrations.AlterField(
            model_name='commander',
            name='img',
            field=models.ImageField(upload_to='cmdr/'),
        ),
    ]
