# Generated by Django 4.1.2 on 2022-10-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InaraApp', '0005_remove_ships_img_alter_commander_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='img',
        ),
    ]
