# Generated by Django 4.1.2 on 2022-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InaraApp', '0006_remove_commander_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='pub_date',
            field=models.DateField(blank=True),
        ),
    ]
