# Generated by Django 4.1.2 on 2022-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InaraApp', '0007_alter_commander_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ships',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
